[env:uno]
platform = atmelavr
board = uno
framework = arduino

upload_speed = 115200
monitor_speed = 115200
; upload_port = /dev/ttyACM0  ; Arduino Uno port

lib_deps = 
    waspinator/AccelStepper@^1.64
